name: Generate HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 11

      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v2
        with:
          accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
          projKey: default
          outputDir: "ld_code_refs"
