name: Generate HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 11

      - name: Install ld-find-code-refs
        run: |
          wget -O ld-find-code-refs https://github.com/launchdarkly/ld-find-code-refs/releases/download/v2.12.0/ld-find-code-refs_2.12.0_linux_amd64.tar.gz
          chmod +x ld-find-code-refs
          sudo mv ld-find-code-refs /usr/local/bin/

      - name: Run ld-find-code-refs
        run: |
          ld-find-code-refs \
          --accessToken=${{ secrets.LD_ACCESS_TOKEN }} \
          --projKey=default \
          --repoName=ReportGenerator \
          --dir=./ \
          --outDir=ld_code_refs
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
