name: Generate HTML and Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name (e.g., owner/repo)'
        required: true
        default: 'owner/repo'
      branch_name:
        description: 'Branch name'
        required: true
        default: 'main'

jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Display Inputs
        run: |
          echo "Branch: ${{ github.event.inputs.branch_name }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - name: Install Python dependencies
        run: |
          pip install pandas
          pip install -r requirements.txt
  
      - name: Extract Repository Name
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          repo_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          echo "Repository Name: $repo_name"
          echo "REPO_NAME=$repo_name" >> $GITHUB_ENV

      - name: Create Output Directory
        run: mkdir -p ld_code_refs

      - name: Run ld-find-code-refs in Docker
        run: |
          docker run --rm \
          -v "$(pwd)":/workspace \
          -w /workspace \
          launchdarkly/ld-find-code-refs \
          --accessToken=${{ secrets.LD_ACCESS_TOKEN }} \
          --projKey=default \
          --repoName=${{ env.REPO_NAME }} \
          --dir=./ \
          --outDir=ld_code_refs
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
      
      - name: Generate HTML from CSV
        run: |
          python generate_html.py ld_code_refs/coderefs__ReportGenerator_main.csv ld_code_refs/index.html ${{ env.REPO_NAME }} ${{ github.event.inputs.branch_name }}
  
      - name: List Output Directory
        run: ls -la ld_code_refs
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ld_code_refs
          publish_branch: gh-pages