name: Generate HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 11

      - name: Create Output Directory
        run: mkdir -p ld_code_refs

      - name: Run ld-find-code-refs in Docker
        run: |
          docker run --rm \
          -v "$(pwd)":/workspace \
          -w /workspace \
          launchdarkly/ld-find-code-refs \
          --accessToken=${{ secrets.LD_ACCESS_TOKEN }} \
          --projKey=default \
          --repoName=ReportGenerator \
          --dir=./ \
          --outDir=ld_code_refs
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
          
      - name: Generate HTML from CSV
        run: |
          python generate_html.py --input ld_code_refs/coderefs__ReportGenerator_main.csv --output ld_code_refs/index.html
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ld_code_refs